### ISSUE TITLE
If queries/constraints return strings containing special character,s HTML report task throws an error and breaks.

### ISSUE THREAD

**Issue by hmozaffari** [jQAssistant/jqa-core-framework#107] opened 2024-06-21 20:13 UTC
If queries/contraints return strings with some special characters such as Unicode 0x13 following line of code throws an exception when running report task:

https://github.com/jQAssistant/jqa-core-framework/blob/ec1c6795ec0eb0a058f4f9de879b74d37dcd7f6c/report/src/main/java/com/buschmais/jqassistant/core/report/impl/HtmlReportTransformer.java#L51

`ERROR:  com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: An invalid XML Character (Unicode: 0x13) was found in the element content of the document
`

Ideally should it ignore those characters when transforming XML to HTML report?

**Comment by DirkMahler** [comment] 2024-06-22 10:03
Looks like invalid encoding somewhere in reading the rules, writing the XML report or doing the XSL transformation to HTML. Will have a look at the pipeline.

**Comment by DirkMahler** [comment] 2024-06-22 15:05
Just verified but cannot reproduce (on a linux system). Can you provide a bit more context (e.g. OS, the source containing extra characters, e.g. Java class, etc), maybe even a little demonstrator project?

**Comment by hmozaffari** [comment] 2024-06-22 17:16
I was using Git plugin and it happend when a commit message had 0x13 character in it. When I checked "report/jqassitant-report.xml" file I was able to find the 0x13 character in xml file but seems when it tried to transform it to html it failed. It failed both on Linux and Windows.

I guess you can reproduce it if you create a dummy neo4j node, use DC3 (0x13) character  in one of its attributes like name, then create a concept or query returning that attirbute.

**Comment by DirkMahler** [comment] 2024-06-24 15:45
The fix has been implemented and is available in the latest 2.3.0-SNAPSHOTS (https://oss.sonatype.org/content/repositories/snapshots/com/buschmais/jqassistant/cli/jqassistant-commandline-neo4jv5/2.3.0-SNAPSHOT/). Would you be able to verify it?

**Comment by hmozaffari** [comment] 2024-06-26 01:15
To test it do I need to re-create the database with 2.3.0-SNAPSHOTS by scanning or I can import an existing database to 2.3.0-SNAPSHOT instant and just run "jqassistant report" command?

**Comment by hmozaffari** [comment] 2024-06-26 14:19
I regenerated the database and performed scan, analyze, report tasks. I confirm special characters are no longer shown in XML file and report task passes.  Thanks for fixing it!

**Comment by DirkMahler** [comment] 2024-06-27 15:23
Thanks for the feedback!

**Closed by DirkMahler** 2024-06-27 15:23 UTC
Labels: type:bug

**Comment by DirkMahler** [comment] 2024-07-02 07:00
jQA 2.3.1 is now available, containing the fix.
